version: "3.4"

networks:
  internal:

services:

  nginx:
    build:
      context: .
      target: phraseanet-doc-nginx
    image: local/nginx:latest
    restart: on-failure
    volumes:
    - ./_build/html:/usr/share/nginx/html
    environment:
    - PHRASEANET_DOC_NGINX_PORT
    ports:
      - ${PHRASEANET_DOC_NGINX_PORT}:80
    networks:
      - internal

  phraseanet-doc-builder:
    build:
      context: .
      target: phraseanet-doc-builder
    image: phraseanet-doc-builder
    restart: on-failure
    volumes:
      - ./_build:/docs/_build:rw
    networks:
      - internal